#!/bin/bash

wget https://dwm.suckless.org/patches/actualfullscreen/dwm-actualfullscreen-20211013-cb3f58a.diff
wget https://dwm.suckless.org/patches/alpha/dwm-alpha-20230401-348f655.diff
wget https://dwm.suckless.org/patches/alttab2/dwm-alttab2-6.4.diff
wget https://dwm.suckless.org/patches/alwayscenter/dwm-alwayscenter-20200625-f04cac6.diff
wget https://dwm.suckless.org/patches/autostart/dwm-autostart-20210120-cb3f58a.diff
wget https://dwm.suckless.org/patches/awesomebar/dwm-awesomebar-20230431-6.4.diff
wget https://dwm.suckless.org/patches/bar_height/dwm-bar-height-6.2.diff
wget https://dwm.suckless.org/patches/barpadding/dwm-barpadding-20211020-a786211.diff
wget https://dwm.suckless.org/patches/bartoggle/dwm-bartoggle-6.4.diff
wget https://dwm.suckless.org/patches/cyclelayouts/dwm-cyclelayouts-20180524-6.2.diff
wget https://dwm.suckless.org/patches/dragmfact/dwm-dragmfact-6.2.diff
wget https://dwm.suckless.org/patches/fakefullscreen/dwm-fakefullscreen-20210714-138b405.diff
wget https://dwm.suckless.org/patches/launcher/dwm-launchers-20200527-f09418b.diff
wget https://dwm.suckless.org/patches/launcher-colors/dwm-launchers-colors-20231221-81aca1b.diff
wget https://dwm.suckless.org/patches/movestack/dwm-movestack-20211115-a786211.diff
wget https://dwm.suckless.org/patches/restartsig/dwm-restartsig-20180523-6.2.diff
wget https://dwm.suckless.org/patches/rotatestack/dwm-rotatestack-20161021-ab9571b.diff
wget https://dwm.suckless.org/patches/selfrestart/dwm-r1615-selfrestart.diff
wget https://dwm.suckless.org/patches/shift-tools/dwm-shif-tools-6.2.diff
wget https://dwm.suckless.org/patches/shift-tools/shift-tools.c
wget https://dwm.suckless.org/patches/status2d/dwm-status2d-systray-6.4.diff
wget https://dwm.suckless.org/patches/systray/dwm-systray-20230922-9f88553.diff
wget https://dwm.suckless.org/patches/tag-previews/dwm-tag-preview-6.3.diff
wget https://dwm.suckless.org/patches/underlinetags/dwm-underlinetags-6.2.diff
wget https://dwm.suckless.org/patches/vanitygaps/dwm-cfacts-vanitygaps-6.4_combo.diff
wget https://dwm.suckless.org/patches/winicon/dwm-winicon-6.3-v2.1.diff
wget https://dwm.suckless.org/patches/winview/dwm-6.0-winview.diff
wget https://dwm.suckless.org/patches/zoomswap/dwm-zoomswap-6.2.diff
wget https://dwm.suckless.org/patches/launcher-colors/dwm-launchers-colors-20231221-81aca1b.diff
